### ISSUE TITLE
data[id] can not be found?

### ISSUE THREAD

**Issue by bvdkerkhof** [custom-components/sensor.untapped#7]
Downloaded the raw component in custom_components/sensor/untappd.py but after restarting (several times) it keeps giving the error below (Invalid Config)

`Invalid config for [sensor.untappd]: required key not provided @ data['id']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/sensor.untappd/`

Running Home Assistant on Pi with 0.74

**Comment by swetoast** [comment]
did you add the api key and secret key provided by untappd in your config file?

**Comment by bvdkerkhof** [comment]
Yes through the secrets file. Api key is working as i'm polling the api myself through HA with rest sensor but a sensor is more usefull then 3 rest api sensors to pull some info

**Comment by swetoast** [comment]
does any of the data show up under dev-info when the component is loaded?

**Comment by swetoast** [comment]
looks like it might be some configuration problem since its stating that it doesnt get any data

**Comment by ludeeus** [comment]
@bvdkerkhof That error only show _if_ you have miss-configured the platform.
Paste your configuration here, as a reference this is how mine looks:
```yaml
sensor:
  - platform: untappd
    username: !secret sensor_untappd_username
    id: !secret sensor_untappd_id
    secret: !secret sensor_untappd_secret
```
